### PR TITLE
I have completed

### PR DESCRIPTION
**Pull request by kelvinparmar**
## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Dun-sin** [comment]
Please do it again and follow the instructions in the pull request template.

Thank you

**Comment by kelvinparmar** [comment]
Please tell me what mistake I have done?
I know that Commit title mistake but another is what?

**Comment by Dun-sin** [comment]
when you made a pull request, you saw something like this:
image

read it and follow the instructions, 

`fixes issues` means the issue number in this case it's #9 (click on it and see)

`changes proposed`means add the changes you made in the project, in your case should be added icons or some to the readme

just follow the rest of the instructions

**Comment by kelvinparmar** [comment]
What I have changed in Readme and icons that's all are right or wrong?

**Comment by Dun-sin** [comment]
> What I have changed in Readme and icons that's all are right or wrong?

it's okay, but @dhrumishah did it already and followed the pull request rules, so i picked merged hers

**Comment by kelvinparmar** [comment]
I want to see that

**Comment by Dun-sin** [comment]
hers?

**Comment by kelvinparmar** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Dun-sin** [comment]
https://github.com/Dun-sin/anon-chat-app/pull/17

here you go

**Pull request closed without merging**
